global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'inventory-service'
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['prometheus.railway.internal']
